workspace:
  base: /go
  path: src/github.com/purepennons/upload2gcs

matrix:
  GITHUB_REPO:
    - purepennons/upload2gcs
  GCS_FOLDER:
    - /folder

pipeline:
  test:
    image: golang:1.8
    environment:
      - CGO_ENABLED=0
    commands:
      - go get
      - go build -o drone-upload2gcs
      # - touch drone-upload2gcs

  # publish:
  #   image: plugins/docker
  #   repo: purepennons/upload2gcs
  #   password: ${DOCKER_PASSWORD}
  #   email: ${DOCKER_EMAIL}
  #   username: ${DOCKER_USERNAME}
  #   tags: latest
  #   when:
  #     branch: master
  #     event: push


# plugin:
#   name: GCS
#   desc: Upload a file to Google Cloud Storage
#   type: publish
#   image: ${GITHUB_REPO}
#   labels:
#     - publish
#     - google cloud
#     - gcp
#     - gcs

  gcs:
    image: wyattjoh/drone-gcs
    acl: private
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS_CONTENTS}
    bucket: "qeek-testbed.appspot.com"
    source: ./drone-upload2gcs
    strip_prefix: /private
    target: $GCS_FOLDER

